"""order

Revision ID: 2ea9f86f6014
Revises: aaf1bdd3e5b6
Create Date: 2026-03-25 18:09:50.626061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea9f86f6014'
down_revision: Union[str, Sequence[str], None] = 'aaf1bdd3e5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('placed', 'preparing', 'shipped', 'delivered', 'cancelled', name='order_status', native_enum=False, create_constraint=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
