"""empty message

Revision ID: a0bf18c4505d
Revises: 869b8d7c6d3a
Create Date: 2026-03-20 16:20:52.895514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0bf18c4505d'
down_revision: Union[str, Sequence[str], None] = '869b8d7c6d3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('green_beans', sa.Column('stock_kg', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('green_beans', sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('green_beans', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('CUSTOMER', 'ADMIN', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('green_beans', 'description')
    op.drop_column('green_beans', 'price_per_kg')
    op.drop_column('green_beans', 'stock_kg')
    # ### end Alembic commands ###
