"""order

Revision ID: aaf1bdd3e5b6
Revises: e60a33e8eb58
Create Date: 2026-03-25 18:09:32.466243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf1bdd3e5b6'
down_revision: Union[str, Sequence[str], None] = 'e60a33e8eb58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.VARCHAR(length=9), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
