"""empty message

Revision ID: b36a6f1528da
Revises: a0bf18c4505d
Create Date: 2026-03-20 17:02:48.905669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36a6f1528da'
down_revision: Union[str, Sequence[str], None] = 'a0bf18c4505d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('green_beans', sa.Column('process', sa.String(length=100), nullable=False))
    op.drop_column('green_beans', 'proccess')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('green_beans', sa.Column('proccess', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('green_beans', 'process')
    # ### end Alembic commands ###
